/**
 * Downloads the latin subsets of our two display fonts and self-hosts them.
 *
 * Why self-hosted instead of a <link> to fonts.googleapis.com:
 *  - guarantees the font request is same-origin, so <link rel=preload> actually helps
 *  - removes a third-party DNS/TLS/connection from the critical path (Lighthouse)
 *  - lets us emit a single variable-font file for Space Grotesk (3x -> 1x bytes)
 *
 * Only the `latin` subset is kept. Other subsets are dead weight for this site and
 * are never matched by the unicode-range, so shipping them would be pure waste.
 *
 * Run: node scripts/fetch-fonts.mjs
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Space+Grotesk:wght@400;500;700&display=swap';
const WANTED_SUBSETS = new Set(['latin']);
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const root = path.resolve(import.meta.dirname, '..');
const fontDir = path.join(root, 'public', 'fonts');
const outFile = path.join(root, 'src', 'styles', 'fonts.css');

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

/** @type {{family:string,weight:string,url:string,range:string,file:string,bytes:number}[]} */
const faces = [];
const written = new Map(); // hash -> filename (dedupes variable fonts)

for (const [, subset, block] of await get(CSS_URL).then((css) =>
  css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g),
)) {
  if (!WANTED_SUBSETS.has(subset)) continue;
  const pick = (re) => block.match(re)?.[1]?.trim();
  faces.push({
    family: pick(/font-family:\s*'([^']+)'/),
    weight: pick(/font-weight:\s*(\d+)/),
    url: pick(/url\((https:[^)]+\.woff2)\)/),
    range: pick(/unicode-range:\s*([^;]+);/),
  });
}

for (const face of faces) {
  if (!face.family || !face.url) throw new Error(`could not parse @font-face: ${face.url}`);

  let entry = written.get(face.url);
  if (!entry) {
    const buf = await get(face.url, true);
    const hash = createHash('sha256').update(buf).digest('hex');
    const file = `${face.family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${hash.slice(0, 8)}.woff2`;
    await fs.mkdir(fontDir, { recursive: true });
    await fs.writeFile(path.join(fontDir, file), buf);
    entry = { file, bytes: buf.length };
    written.set(face.url, entry);
    // Merge weights that resolve to the same physical file into a variable range.
    entry.weights = new Set();
    console.log(`  ${file.padEnd(40)} ${buf.length.toLocaleString()} bytes`);
  }
  entry.weights.add(Number(face.weight));
  face.file = entry.file;
}

// Group faces that share a file so Space Grotesk becomes one variable @font-face.
const groups = new Map();
for (const f of faces) {
  if (!groups.has(f.file)) groups.set(f.file, []);
  groups.get(f.file).push(f);
}

const css = [
  '/* AUTO-GENERATED by scripts/fetch-fonts.mjs - do not edit by hand. */',
  '/* Self-hosted latin subsets. font-display:swap + preload in index.html = no FOIT,',
  '   and a single variable file for Space Grotesk keeps the font payload at ~35KB. */',
  '',
  ...[...groups.values()].map((group) => {
    const weights = group.map((f) => Number(f.weight)).sort((a, b) => a - b);
    const variable = weights.length > 1;
    return `@font-face {
  font-family: '${group[0].family}';
  font-style: normal;
  font-weight: ${variable ? `${weights[0]} ${weights.at(-1)}` : weights[0]};
  font-display: swap;
  src: url('/fonts/${group[0].file}') format('woff2');
  unicode-range: ${group[0].range};
}`;
  }),
].join('\n\n');

await fs.mkdir(path.dirname(outFile), { recursive: true });
await fs.writeFile(outFile, css + '\n', 'utf8');

const total = [...written.values()].reduce((n, e) => n + e.bytes, 0);
console.log(`\n${written.size} font file(s), ${(total / 1024).toFixed(1)} KB total`);
console.log(`wrote ${path.relative(root, outFile)}`);
